### ISSUE TITLE
Is there any working examples of how to create an issue with complete labels?

### ISSUE THREAD

**Issue by E3V3A** [octokit/octokit.rb#1002]
I'm looking to create a new issue that also include all the label tags: `name`, `color` and `description`.
Are there any working examples anywhere? 

PS. I have already attempted this (as mentioned in #1001), but colors and description seem to be ignored in the creation process.

**Comment by tarebyte** [comment]
@E3V3A it's currently not possible in the GitHub API to create new labels while specifying the color and description. There is a limitation in the API right now that you can only set the name.

You would be better off making an API request to create the labels first, and then create the issues with the labels you created.

Something like this:

```ruby
# frozen_string_literal: true

require 'octokit'

client = Octokit::Client.new(access_token: ENV['GITHUB_TOKEN'])

REPO_NAME_WITH_OWNER = 'OWNER/REPO'.freeze

label = client.add_label(REPO_NAME_WITH_OWNER, 'octokit-test', '8f57aa',
                         accept: 'application/vnd.github.symmetra-preview+json',
                         description: 'A test for the Octokit client')

client.create_issue(REPO_NAME_WITH_OWNER, 'your title', 'The body', labels: [label.name])
```

---

As a side note I really would have appreciated you waiting in your original issue rather than opening up a new one. If you wanted to continue the discussion I would've been happy to reopen it.
