### ISSUE TITLE
New delete_pull_request_review_request method doesn't match api

### ISSUE THREAD

**Issue by latentflip** [octokit/octokit.rb#1037]
I think the logic for the new method for deleting multiple pull request reviewers is wrong when you want to also remove team reviewers.

https://github.com/octokit/octokit.rb/blob/eba9b41bfe78d34c5ec57a075ab833e91d24179c/lib/octokit/client/reviews.rb#L173-L184

The example params show:

```
   reviewers = { 
     "reviewers" => [ "octocat", "hubot", "other_user" ], 
     "team_reviewers" => [ "justice-league" ] 
   }
```

which is exactly the structure we [expect in the api](https://developer.github.com/v3/pulls/review_requests/#delete-a-review-request)

for some reason we are using `reviewers.values.flatten` which just joins both lists together, and then sends it through as reviewers, so we end up sending: 
```
{ reviewers: ["octocat", "hubot", "other_user", "justice-league"] }
```

which means that the team reviewer (`justice-league`) is thrown away.

I think if we just change the line to `options.merge(reviewers)`, or just drop the reviewers param altogether and pass it through as options, this will work as expected?

**Comment by tarebyte** [comment]
> I think if we just change the line to `options.merge(reviewers)`,

That sounds like a good plan to me, mind opening up a pull request?

**Comment by latentflip** [comment]
>> I think if we just change the line to options.merge(reviewers),

> That sounds like a good plan to me, mind opening up a pull request?

@tarebyte now that I look at it again, I wonder if just dropping the reviewers arg would be better? Having two separate hashes as arguments one after the other, which are then just merged could be awkward? Do we handle cases like this somewhere else?

I can open the PR for the change, but I'm not sure that I have time at the moment to figure out how to change the tests to actually assert for this, and do the VCR stuff etc as I've never worked on this repo before.

---

It looks like the create pull request reviewers will also not support creating team requests, and might need a similar change?

https://github.com/octokit/octokit.rb/blob/eba9b41bfe78d34c5ec57a075ab833e91d24179c/lib/octokit/client/reviews.rb#L154-L162

**Comment by kytrinyx** [comment]
@latentflip @tarebyte I will see if I can get a PR in for this for open source Friday

**Comment by kytrinyx** [comment]
My Friday got away from me. I'm taking a stab at it today.

**Comment by kytrinyx** [comment]
We're going to need to make two adjustments.

1. The _create a review request_ (`request_pull_request_review`) method currently takes an array of `reviewers`. This will need to be deprecated and `:reviewers` should be added to the `options` hash.
1. The _delete a review request_ (`delete_request_pull_request_review`) method needs to deprecate the `reviewers` hash, adding it to the options hash.

In both cases the change needs to be made in a backwards-compatible way so that any clients that are still using the old method signature don't break.

As a separate note, the `delete_pull_request_review_request` has incorrectly documented the method name in the example, referring to it as `delete_request_pull_request_review`.

**Comment by kytrinyx** [comment]
Quick update: I'm pretty sure I have working code, but I can't regenerate valid VCR cassettes for CI. @tarebyte and I are pairing tomorrow to get it sorted.

**Comment by kytrinyx** [comment]
We sorted it!

I'll be cutting a release in the next day or so (back to back meetings today, otherwise I'd do it now).
