### ISSUE TITLE
Intermittent test failure on Ruby 2.2.x

### ISSUE THREAD

**Issue by JuanitoFatas** [octokit/octokit.rb#1048]
Open this issue for future investigations.

This test:

https://github.com/octokit/octokit.rb/blob/b57d51bc3f810aeb39a8029654c1139ba1f1caa2/spec/octokit/client_spec.rb#L314-L317

sometimes failed:

```
Failures:
  1) Octokit::Client.agent caches the agent
     Failure/Error: expect(agent.object_id).to eq(Octokit.client.agent.object_id)
       
       expected: 38691020
            got: 38697860
       
       (compared using ==)
     # ./spec/octokit/client_spec.rb:316:in `block (3 levels) in <top (required)>'
Finished in 32.21 seconds (files took 0.6578 seconds to load)
735 examples, 1 failure
```

From [this build](https://travis-ci.org/octokit/octokit.rb/jobs/413404668).

**Comment by nickfloyd** [comment]
Hey, thanks for the effort here. Given that this issue has been around for a while and many changes have been added since this was first introduced and since we no longer support ruby 2.2, I am going to close this issue and mark it as stale. If you feel strongly about this needing to be implemented please feel free to reopen and make the changes stated above and we’ll do what we can to get it merged in. Thanks again!
