### ISSUE TITLE
makeing a pull request from a fork

### ISSUE THREAD

**Issue by a4z** [octokit/octokit.rb#1109]
I go through the docs, and I see I can make pull requests from a feature branch to master, 
but often the workflow is having a fork, making the branch there, and than send a pull request.
I wonder if there is an API/functionality in octokit.rb that support a pull request from one reop to the 'forked from' one

**Comment by tarebyte** [comment]
@a4z in order to open a pull request from a forked repo to the parent repo it would look something like this:

```ruby
client = Octokit::Client.new(access_token: <YOUR_GITHUB_TOKEN>)

client.create_pull_request("octokit/octokit.rb", "master", "tarebyte:my-feature-branch", "Pull request title", "This is the body of my pull request")
```

The trick here is when you are listing the `head` branch for the pull request you have to provide the login of the account as a prefix.

Check out https://developer.github.com/v3/pulls/#input for more help.

**Comment by a4z** [comment]
this works! thanks a lot!!
