### ISSUE TITLE
Display response and request on error

### ISSUE THREAD

**Issue by native-api** [octokit/octokit.rb#1144]
In GitHub API, headers contain additional information about the error so they are needed for diagnostics.

See e.g. https://travis-ci.community/t/github-returns-404-when-trying-to-deploy-using-github-releases/4770 where the cause is unclear from just the error code.

**Comment by nickfloyd** [comment]
Hey, thanks for the effort here. Given that this issue has been around for a while and many changes have been added since this was first introduced and we've made some [improvements](https://github.com/octokit/octokit.rb/releases) to error handling, I am going to close this issue and mark it as stale. If you feel strongly about this needing to be implemented please feel free to reopen and make the changes stated above and we’ll do what we can to get it merged in. Thanks again!
