### ISSUE TITLE
Where did 4.17.0 go?

### ISSUE THREAD

**Issue by jakeswenson** [octokit/octokit.rb#1219]
I was shocked today to find my builds failing with this:
```
Fetching gem metadata from https://rubygems.org/..........

Your bundle is locked to octokit (4.17.0), but that version could not be found
in any of the sources listed in your Gemfile. If you haven't changed sources,
that means the author of octokit (4.17.0) has removed it. You'll need to update
your bundle to a version other than octokit (4.17.0) that hasn't been removed in
order to install.
```

Why was 4.17 removed from the gem registry? 
Isn't this considered hugely bad practice given builds could be depending on this?

Looking at `rubygems` I no longer see 4.17.0 https://rubygems.org/gems/octokit
#1209 Documents that 4.17 was released. Yet I don't see it in the releases section: https://github.com/octokit/octokit.rb/releases

Ultimately i'd love to use this issue to:
- [x] document why this release was pulled
- [ ] get a commitment from the maintainers that this is a practice that should be avoided in the future

**Comment by jakeswenson** [comment]
`rubygems` confirms it was yanked: https://rubygems.org/gems/octokit/versions/4.17.0

**Comment by tarebyte** [comment]
> * document why this release was pulled

We had to pull it because there was broken API calls. See https://github.com/octokit/octokit.rb/pull/1218 for more details.

> * get a commitment from the maintainers that this is a practice that should be avoided in the future

We can try and avoid it, but that's not something we can guarantee. In the event we've broken a client with incorrect API calls we will need to pull the version. I'm sorry for your frustration but there isn't really a better way to do this.

**Comment by jakeswenson** [comment]
Thank you @tarebyte for the quick response. I understand that it doesn't feel good to have released/published a broken package, and it could lead to more frustration/issues if folks depend on it not knowing its broken. However the bugs were not affecting my use of this package (currently.)

Don't you think it'd be good to have a well documented practice in place for these types of situations?
For example it would have been nice if I could have gone to the [`releases`](https://github.com/octokit/octokit.rb/releases), seen that `4.17.0` was marked as `Depricated` or `Broken` and then I would seen an updated release description pointing me at the reason (in this case a link to the PR #1218).

I am sure we all remember the [`left-pad` incident](https://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm) and recognize how its a bad idea to yank packages. In fact `npm` [updated its policy](https://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy) to prohibit `yanking`/`unpublishing` a package after that.

The in fact document their policy in that blog: 
> Supreet realizes that there are several serious bugs in 1.0.0 and would like to completely unpublish the version. He attempts to unpublish and is prompted to talk to support@npmjs.com because the 1.0.0 version of his package is older than 24 hours. Instead, Supreet publishes a new version with bug fixes, 1.0.1.

I think it'd be good for this project to document its practices for these types of situations going forward.

**Comment by tarebyte** [comment]
@jakeswenson thanks for taking the time to give us that feedback. We'll certainly take this under advisement.

I think the happy path here would be to keep the release with a note about how it's broken and then remove the package from ruby gems.

Looking at https://github.com/lostisland/faraday/releases/tag/v0.17.0 as an example this feels like a good way to go. It stops folks from downloading it but doesn't leave it as a mystery as to what happened.

**Comment by tarebyte** [comment]
I've put back https://github.com/octokit/octokit.rb/releases/tag/v4.17.0 and have made a note.

**Comment by caramcc** [comment]
Due respect, yanking this version from RubyGems is not "happy path" for anyone who's using it. This resulted in broken builds for a lot of applications that we needed to scramble to fix.

In the Faraday example that you gave above, note that even though the 0.17.0 was published as a "rollback release" to undo all of the changes that were shipped in their 0.16.x release series, **none of the 0.16.x versions were removed from RubyGems.** You could still install them today, even though those changes were rolled back in a later version. ([see available versions on rubygems](https://rubygems.org/gems/faraday/versions))

Once a version of any package is published to a given package repository, it is load-bearing. Especially a popular gem like octokit, which had close to 300,000 downloads for 4.17.0.

To clarify, it's expected that future versions of octokit could potentially be yanked, correct?

If so, could you document the cases in which a version might be yanked so that users of this gem can reassess whether or not they want to continue depending on a package that might disappear without warning because they contain bugs?

**Comment by SuperTux88** [comment]
> I've put back https://github.com/octokit/octokit.rb/releases/tag/v4.17.0 and have made a note.

It's still missing on rubygems.org and therefore apps that still depend on 4.17.0 and weren't affected by the bug are broken now. Please avoid yanking versions in the future, it almost always makes the situation worse than without yanking it.

**Comment by rohitpaulk** [comment]
Ended up here because of a broken build. Appreciate the steps you've taken to document the issue :+1: 

My 2 cents - unless there's a critical security vulnerability, not yanking is probably a better choice. The `left-pad` article linked above explains the issue better than I possibly could :slightly_smiling_face:

**Comment by tarebyte** [comment]
Thank you all for your feedback, it's something we will no doubtably take account into the future.
