### ISSUE TITLE
It doesn't reflect changes to default_adapter

### ISSUE THREAD

**Issue by ioquatix** [octokit/octokit.rb#1238]
https://github.com/octokit/octokit.rb/blob/14bb1a1d4fec8d2250dc6f6b9cb2d446a0332d58/lib/octokit/default.rb#L32

If the user changes default adapter AFTER loading this file, it is not used.

**Comment by nickfloyd** [comment]
Hey, thanks for the effort here. Given that this issue has been around for a while and many changes have been added since this was first introduced, I am going to close this issue and mark it as stale. If you feel strongly about this needing to be implemented/asked please feel free to reopen and make the changes stated above and we’ll do what we can to get it merged in. Thanks again!

**Comment by ioquatix** [comment]
I think this is the same problem:

https://github.com/octokit/octokit.rb/blob/master/lib/octokit/default.rb#L32

You either need to (1) initialize it during the class creation or (2) use the default faraday configuration (or both?).

**Comment by ioquatix** [comment]
Probably just dynamically generate it and cache it here:

https://github.com/octokit/octokit.rb/blob/master/lib/octokit/default.rb#L118
