### ISSUE TITLE
How to stub octokit calls?

### ISSUE THREAD

**Issue by bronson** [octokit/octokit.rb#15]
I haven't found a good way to test Octokit usage in my app.  Closest I've come is this:

```
test = Octokit::Client.new :adapter => :test
test.user('bronson')
 => RuntimeError: no stubbed request for get /api/v2/json/user/show/bronson
```

Looks great so far.  I just haven't figured out how to stub that request.  I've tried all sorts of variations mentioned in Faraday's readme, nothing's worked.

Is there a good way to test Octokit calls in my app?

**Comment by maikokuppe** [comment]
Same question here. How to stub octokit requests?

And thinking further, this way of testing doesn't seem to be *right*, because it is based on the current github api implementation (on the urls), which should only be of concern to octokit. Is there a way to catch all the calls to octokit methods which, for example create and delete a branch? This way the testing logic of my app is clearly separated from the testing logic of octokit:

If my app makes the correct calls to octokit methods, and if octokit works correctly, I can be sure that my app works correctly with github.

**Comment by pengwynn** [comment]
@maikokuppe You've got a range of options:

- Stub Octokit calls and trust Octokit is bug free. 😇 
- Stub the HTTP calls with something like [Webmock](https://github.com/bblimke/webmock).
- Make live HTTP calls and record them for subsequent playback (until you refresh your fixtures) with something like [VCR](https://github.com/vcr/vcr).

Octokit itself [uses the latter](https://github.com/octokit/octokit.rb#running-and-writing-new-tests). You'll have to find the right tradeoff that makes sense for your app.

**Comment by maikokuppe** [comment]
Ah, that was lack of knowledge on my side. I didn't know that rspec can simply stub method calls, especially calls to arbitrary Octokit methods.

So option 1 seems to work and is the correct way (because of separation of concerns) in my opinion :)

**Comment by ddosque** [comment]
Option 2 - stub HTTP using Webmock - currently does not work as nicely as I had hoped due to [this webmock issue](https://github.com/bblimke/webmock/issues/449) that has yet to be resolved. I haven't been able to find an answer for that, as it seems to cause the stubbed json string to pass right through into the response, without being correctly parsed.

**Comment by zerogvt** [comment]
A word of caution on using VCR for tests: It seems that VCR is keeping tokens (secrets that is) unencrypted in its cassettes (simple yaml files AFAIK). You can see your tokens if you grep for them in the fixtures folder. Now, assuming that you'll check in the fixtures onto a (probably) public repo you effectively will be exposing your tokens.

**Comment by joho** [comment]
It's possible to work around VCR storing your auth secrets.

I've got a snippet in my `test_helper.rb` that configures VCR like this:
```rb
VCR.configure do |c|
  c.hook_into :webmock
  c.cassette_library_dir = 'test/fixtures/files/cassettes'
  c.filter_sensitive_data('<AUTH_TOKEN>') do |interaction|
    interaction.request.headers['Authorization'].first
  end
end
```
which does the following to my VCR cassettes:
```yaml
    headers:
      Accept:
      - application/vnd.github.machine-man-preview+json
      User-Agent:
      - Octokit Ruby Gem 4.9.0
      Content-Type:
      - application/json
      Authorization:
      - "<AUTH_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
```
