### ISSUE TITLE
[BUG]: Fetch a given reference uses the wrong API

### ISSUE THREAD

**Issue by kitallis** [octokit/octokit.rb#1628]
### What happened?

The following method: https://github.com/octokit/octokit.rb/blob/main/lib/octokit/client/refs.rb#L46 is presumably the analog to this [API](https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#get-a-reference). 

However, the endpoint used is `refs` (plural) not `ref` (singular) which causes this API to behave like the `matching-refs` API, which I think is incorrect since we already have a separate API for that.

We can check that the API does produce unintended output, from this example: https://api.github.com/repos/tramlinehq/ueno/git/refs/tags/v10 (which is what the method uses).

In here, `refs/tags/v10` is not a valid ref in this case.

If this issue seems genuine, happy to drop a PR to correct it.

### Versions

Octokit.rb v7.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @kitallis thank you for bringing this up.  This particular API set is confusing.

So we have all of the GitHub REST API set for [references](https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#about-git-references) - breaking them down below quickly for clarity - It looks like we have a couple of problems.  

All this to say, thank you for being open to get this sorted, please feel free to do so! ❤️ Also, even though this is wrong I'm feeling like it will be a breaking change - we'll version as such so that anyone using these SDKs will have a heads up on the change. 

Here are the details.  Please feel free to correct both implementations if you have time. Head's up on the cassette, they might need to be regenerated. 

- List matching refs:  https://api.github.com/repos/OWNER/REPO/git/matching-refs/REF (supports tag or branch names) 
  - ❌ implemented [here](https://developer.github.com/v3/git/refs/#list-matching-references) -  Incorrectly ("When you use this endpoint without providing a `:ref`, it will return an array of all the references from your Git database, including notes and stashes if they exist on the server.")
  - documented [here](https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#list-matching-references)
- List all matching references:  https://api.github.com/repos/OWNER/REPO/git/matching-refs
  - ✅  implemented [here](https://github.com/octokit/octokit.rb/blob/5d82ffcef142f5bc23e9be016a07c2a34b7a8eb1/lib/octokit/client/refs.rb#L17) 
  - documented [here](https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#list-matching-references)
- Get a reference: https://api.github.com/repos/OWNER/REPO/git/ref/REF  (supports tag or branch names)
  - ❌  implemented [here](https://github.com/octokit/octokit.rb/blob/5d82ffcef142f5bc23e9be016a07c2a34b7a8eb1/lib/octokit/client/refs.rb#L46) - incorrectly (as you pointed out, should be `.../ref/:ref`)
  - documented [here](https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#get-a-reference)
- Create | Update | Delete references all use: HTTP verb +  https://api.github.com/repos/OWNER/REPO/git/refs/REF
  - ✅ implemented [here](https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#create-a-reference) 
  - documented [here](https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#create-a-reference)

Thank you again for helping to make our community better!

**Comment by kitallis** [comment]
Thanks @nickfloyd. 

I had to squint to understand why you pointed out the "List matching refs" to be an incorrect implementation. Just adding some more info here for clarity:

List matching refs is actually just one API. [Documented here](https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#list-matching-references).

This API also claims in the docs, that the `ref` is a required field. While simultaneously saying the bit about `When you use this endpoint without providing a :ref...` etc. Which means it's technically not a required field?

This perhaps means that the octokit interface should either optionally take a ref or implement the two ways as different methods. I will give a shot at "Get a reference" over the weekend since that's my current need. If the others are equally simple to change, I can correct them as well.

**Comment by kitallis** [comment]
This is still on my radar. I will come back to it soon.
