### ISSUE TITLE
@client.org_repos(org_name) returns limited results

### ISSUE THREAD

**Issue by johnnagro** [octokit/octokit.rb#231]
I used to use @client.org_repos(org_name) to walk all our repos to setup some continuous integration in jenkins. In the past that would give me all the repos, now it only returns 30 of them. Unfortunately, I can't tell you how recently that changed (i dont have to run my script very often).

I looked in the docs to see new options were added. I tried with different user permissions. I tried it against our Enterprise install as well as our public GitHub organization. All return no more than 30 repos.

Thanks.

**Comment by slpsys** [comment]
It's worth noting that since this is still the top Google result (at least for me), `auto_traversal` has been renamed to `auto_paginate`: 

    client = Octokit::Client.new(access_token: token, auto_paginate: true)

**Comment by darwin** [comment]
@slpsys Thanks for this note. I have been scratching my head for months why my github automation tasks do not apply to some repos. I had : auto_traversal set to true, so I rejected the possibility that it is due to auto traversal not being applied.

@pengwynn I would recommend making auto_traversal an alias to auto_paginate. For us who do not follow octokit in such detail.
