### ISSUE TITLE
Octokit.configure only way to cache

### ISSUE THREAD

**Issue by joelmoss** [octokit/octokit.rb#359]
So, I've setup Faraday to use caching as detailed in the readme, but this only works when using `Octokit.configure` block, and not `Octokit::Client.new`. Is that intentional?

``` ruby
stack = Faraday::Builder.new do |builder|
  builder.use Faraday::HttpCache, serializer: Oj, logger: Rails.logger
  builder.use Octokit::Response::RaiseError
  builder.adapter Faraday.default_adapter
end
Octokit.middleware = stack
```

This makes call to Github every time and does not cache the second request:

``` ruby
client = Octokit::Client.new(access_token: github_token)
client.user # cache miss
client.user # cache miss
```

This makes a call to Github on only the first request. Al other requests are cached:

``` ruby
Octokit.configure do |c|
  c.access_token: github_token
end
Octokit.user # cache miss
Octokit.user # cache hit
```

**Comment by jrochkind** [comment]
This is super old and probably solved, but you can (at least currently) tell   Faraday::HttpCache to cache "private" things, as a private cache. 

    builder.use Faraday::HttpCache, store: whatever, shared_cache: false

**Comment by kernelsmith** [comment]
I apologize for Zombiefying this thread again, but I was always getting "cache-control => private" in the headers coming back from the server, even tho there wasn't any "private" information. I believe that is because I was accessing "private" repos. Private repos as in "not public" repos, but not private in the "this is my private user info" kind of way. It seems the responses for anything coming from a private repo would get the "private" cache-control directive. In my case I was only accessing & caching for a single user, so there is not threat of leakage, so I found this thread and did change to `shared_cache: false` and all is well.  Thanks @jrochkind
