### ISSUE TITLE
Rate limit resource

### ISSUE THREAD

**Issue by ivantsepp** [octokit/octokit.rb#586]
https://developer.github.com/v3/rate_limit/ endpoint returns information for both core and search API requests. Is there a way to surface the number of search requests you have remaining? I think Octokit has information about core requests (and it looks like it's retrieved from the response headers). 

If Octokit doesn't support this currently, would it be acceptable to change it so that it does?

**Comment by pengwynn** [comment]
Yeah, that resource was expanded after the rate limit helpers were written for Octokit. We may have to ditch the way we read the values from the `last_response` since that last response could be a "core" or "search" resource. Would definitely entertain a patch if you want to open a PR for discussion.

**Comment by ivantsepp** [comment]
Yup! I'll open a pull request one soon, thanks!

**Comment by blunderdome** [comment]
I'm not sure why the referenced PR never made it through, but I would also love to be able to get the search limit remaining.

**Comment by kytrinyx** [comment]
@blunderdome @ivantsepp -- it looks like it was closed due to drift in the codebase. If either of you would be interested in carrying the pull request (see section 4 in https://blog.jessfraz.com/post/the-art-of-closing/) / reimplementing the changes against a fresh master, that would be superb.
