### ISSUE TITLE
no data from client.user.rels[:organizations].get.data

### ISSUE THREAD

**Issue by Elmuch** [octokit/octokit.rb#623]
This endpoint was working for me until recently. Is there something I am missing?

**Comment by pengwynn** [comment]
I suspect [the recent changes][] for direct organization membership might be the problem here. Can you make sure your [token has at least `read:org` scope][scopes]?

[the recent changes]: https://developer.github.com/v3/orgs/#oauth-scope-requirements
[scopes]: https://developer.github.com/v3/orgs/#oauth-scope-requirements

**Comment by Elmuch** [comment]
Thanks @pengwynn. That was my initial thought when I encountered the problem. I re-authenticated my  token and included read:org scope but I still got an empty response. Note: status is 200

**Comment by jessicayang15** [comment]
@Elmuch Are you still seeing this issue?
