### ISSUE TITLE
I can see from the API that i can merge a pull request, can i check for conflicts first ?

### ISSUE THREAD

**Issue by tphoney** [octokit/octokit.rb#626]
I want to check a pull request to see if it is possible to merge that PR. IE if i were to look in github i would see this 

"This branch has conflicts that must be resolved Use the command line"

is there a way to see if a PR has merge conflicts ?

Great API by the way.

**Comment by pengwynn** [comment]
There are a couple of fields on the pull request resource that will indicate [mergeability][]. The `mergeable` field is a Boolean that indicates if the branch can be merged, and `mergeable_state` will indicate if it's `clean`, `dirty`, or `unstable`. 

If the repository is set up for continuous integration, you can use the [Status API][] to check the build status for each commit.

@tphoney, I'm gonna close this one out since it's not an Octokit issue. Feel free to [hit us up at support][support] if you've got more questions. :bow:

[mergeability]: https://developer.github.com/v3/pulls/#mergability
[Status API]: https://developer.github.com/v3/repos/statuses/
[support]: http://git.io/vOCSa

**Comment by tphoney** [comment]
@pengwynn Thanks, i was using the pulls api that did not have the fields i needed. one i use the pull_request call i get the fields i need
