### ISSUE TITLE
GitHub API latest_release result is incorrect

### ISSUE THREAD

**Issue by JuanitoFatas** [octokit/octokit.rb#633]
if you query rspec-rails's [releases](https://api.github.com/repos/rspec/rspec-rails/releases), the result as follows:

```ruby
> client = Octokit::Client.new;
> client.releases("rspec/rspec-rails").collect(&:tag_name)
=> ["v2.99.0.beta2", "v3.0.0.beta2", "v2.14.1", "v2.99.0.beta1", "v3.0.0.beta1", "v2.14.0"]
```

And query [latest_release](https://api.github.com/repos/rspec/rspec-rails/releases/latest):

```ruby
> client.latest_release("rspec/rspec-rails").tag_name
=> "v2.14.1"
```

The result is `"v2.14.1"`, it should be `"3.0.0.beta2"`.

I think the GitHub API should use [version_sorter](https://github.com/github/version_sorter) to return correct result?

**Comment by pengwynn** [comment]
Doesn't appear to be a sorting issue since `3.0.0.beta2` [is a pre-release][releases] and this method ignores those. Since this isn't Octokit-related please [get in touch with Support][support] if you've got API questions or feedback.

[releases]: https://github.com/rspec/rspec-rails/releases?after=v3.0.2
[support]: https://github.com/contact?form%5Bsubject%5D=Releases+API

**Comment by JuanitoFatas** [comment]
Ah ok, pre-release! Sorry for the disturbance!
