### ISSUE TITLE
Private repositories not being listed

### ISSUE THREAD

**Issue by jsvgoncalves** [octokit/octokit.rb#646]
I've created a token with the necessary permissions to read from private repos.

However, when running the code below I only get my public repositories.

Any thoughts?

```ruby
#!/usr/bin/ruby
require 'octokit'

# Provide authentication credentials
client = Octokit::Client.new(
  :login => 'user',
  :access_token => 'token')

repos = client.list_repos('user', :per_page => 100)
puts repos.length
repos.each do |repo|
    puts repo.name
end
```

**Comment by pengwynn** [comment]
@jsvgoncalves That call is a little janky because of how the API changed out from under Octokit between v2 and v3. Passing a username is going to call "GET /users/:user/repos" which [only returns public repos][docs]. Try calling `client.list_repos(nil, :per_page => 100)` to call "GET /user/repos" instead. 

A patch would be welcome to change the method signature to accept a splat so we could extract the options and avoid having to pass the ugly `nil`. 

[docs]: https://developer.github.com/v3/repos/#list-user-repositories
