### ISSUE TITLE
paginate behaves strange with a block

### ISSUE THREAD

**Issue by hannesg** [octokit/octokit.rb#659]
Hi

I try to use the paginate method with auto_pagination to process commits in chunks. The paginate method however behaves very strange when a block is passed to it. If all items fit in the first chunk, paginate doesn't yield but just returns them. Otherwise it yields all chunks one by one as expected.

Cheers'
Hannes

**Comment by joeyw** [comment]
@hannesg Hi Hannes. The block for paginate is intended for combining response data in special cases, mainly the [search api](https://github.com/octokit/octokit.rb/blob/d47cdbb8a5aae81feeae47f712606e8ec32a62bf/lib/octokit/client/search.rb#L70-L72) for example. It is correct that it does not yield when all the results fit into one request, because there is no need to yield the request to combine it with another. If you believe this to be incorrect please open another issue with some code samples. As for processing in chunks, I would recommend splitting the data after you get it from octokit.
