### ISSUE TITLE
Connecting to a GitHub Enterprise server with self-signed certificate

### ISSUE THREAD

**Issue by BanzaiMan** [octokit/octokit.rb#718]
When connecting to a GitHub Enterprise server with self-signed certificate, we get an SSL connexion error (https://github.com/travis-ci/dpl/issues/344#issuecomment-171398198).

If we are on the trusted network, what is the best way to get around this error? Setting

```ruby
client.connection_options[:ssl] = { :verify => false }
```

is certainly one, but I would like to avoid it if we can.

**Comment by pengwynn** [comment]
@BanzaiMan this is the only way I know of with a self-signed cert. I'm going to use a :phone:-a-:octocat: and ask @davideg or @dbussink for ideas.

**Comment by joeyw** [comment]
@BanzaiMan This issue isnt with octokit or ruby in particular, but certificates in general on your machine.

Without installing your own Root Trust CA on the client machine, it has no idea that it can trust your server's certificate because it was not signed by its known certificate authorities (ie self signed). 

You can install the single self signed certificate on the client machine as trusted root certificate. 

Or you can create your own certificate authority, you would then need to install the single Root CA certificate on the machine(s), and going forward any certificates signed by your CA would be accepted.

**Comment by davideg** [comment]
I agree with @joeyw. If you don't want to skip the verification step then you need to make sure the client computers trust your server's certificate.

**Comment by BanzaiMan** [comment]
Hello! Thanks for the input. I'll advise installing the self-signed certificate to the CA.

**Comment by geekflyer** [comment]
@BanzaiMan I can install the certificate into the travis master and workers, but it needs to be propagated into the travis build containers I guess. Is there a way travis enterprise could do this automatically?
