### ISSUE TITLE
exception when using pp

### ISSUE THREAD

**Issue by zenspider** [octokit/octokit.rb#859]
This might be considered a "feature"... but it could be a lot more graceful about it.

```
ruby -roctokit -rpp -e 'auth = `git config github.oauth-token`.chomp; pp Octokit::Client.new access_token: auth'
/Users/ryan/.rbenv/versions/2.4.0/lib/ruby/2.4.0/prettyprint.rb:180:in `text': undefined method `length' for nil:NilClass (NoMethodError)
	from /Users/ryan/.rbenv/versions/2.4.0/lib/ruby/2.4.0/pp.rb:315:in `pretty_print'
	from /Users/ryan/.rbenv/versions/2.4.0/lib/ruby/2.4.0/pp.rb:188:in `block in pp'
	from /Users/ryan/.rbenv/versions/2.4.0/lib/ruby/2.4.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /Users/ryan/.rbenv/versions/2.4.0/lib/ruby/2.4.0/prettyprint.rb:280:in `nest'
	from /Users/ryan/.rbenv/versions/2.4.0/lib/ruby/2.4.0/prettyprint.rb:252:in `block in group'
	from /Users/ryan/.rbenv/versions/2.4.0/lib/ruby/2.4.0/prettyprint.rb:265:in `group_sub'
	from /Users/ryan/.rbenv/versions/2.4.0/lib/ruby/2.4.0/prettyprint.rb:251:in `group'
	from /Users/ryan/.rbenv/versions/2.4.0/lib/ruby/2.4.0/pp.rb:188:in `pp'
	from /Users/ryan/.rbenv/versions/2.4.0/lib/ruby/2.4.0/pp.rb:100:in `block in pp'
	from /Users/ryan/.rbenv/versions/2.4.0/lib/ruby/2.4.0/pp.rb:147:in `guard_inspect_key'
	from /Users/ryan/.rbenv/versions/2.4.0/lib/ruby/2.4.0/pp.rb:100:in `pp'
	from /Users/ryan/.rbenv/versions/2.4.0/lib/ruby/2.4.0/pp.rb:22:in `block in pp'
	from /Users/ryan/.rbenv/versions/2.4.0/lib/ruby/2.4.0/pp.rb:21:in `each'
	from /Users/ryan/.rbenv/versions/2.4.0/lib/ruby/2.4.0/pp.rb:21:in `pp'
	from -e:1:in `<main>'
```

**Comment by kytrinyx** [comment]
No, I don't think this is by design. It's blowing up here:

https://github.com/ruby/ruby/blob/trunk/lib/pp.rb#L315

This is in the object mixin, so `self` is the octokit client.

The octokit client has defined an inspect method, so it shouldn't be returning nil.
https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client.rb#L127-L143

I don't understand what is going on, but the output of the inspect method changes after this line is called:

https://github.com/ruby/ruby/blob/trunk/lib/pp.rb#L164-L166

Before calling that line, we get the usual client inspect output. After that line is called, `client.inspect` returns `nil`.

Then this line gets called:
https://github.com/ruby/ruby/blob/trunk/lib/pp.rb#L188
which is the method which is blowing up (linked to at the start).
