### ISSUE TITLE
Updating a team member's role

### ISSUE THREAD

**Issue by hyandell** [octokit/octokit.rb#967]
I was recently scripting a change to update team member's role to maintainers. 

There are two functions in organizations.rb that look like they would do this:

add_team_member
add_team_membership

In both cases an example would be useful (happy to PR).

The add_team_member function appears to be for adding existing org-members, while add_team_membership is implied to be for adding non-org-members. 

When passing in a :role => :maintainer, I found that the opposite was true. add_team_member had no effect, while add_team_membership worked very nicely.

Is there a deeper explanation of the reason for these two functions somewhere? Am I confused above unnecessarily?

**Comment by tarebyte** [comment]
@hyandell I think there is some confusion here because those functions are actually two different API's

Source and documentation links for referral:

https://developer.github.com/v3/orgs/teams/#add-team-member
https://github.com/octokit/octokit.rb/blob/ae1636f71fb02e0b858f54f755b5701d5fcb06ac/lib/octokit/client/organizations.rb#L392-L418

https://developer.github.com/v3/orgs/teams/#add-or-update-team-membership
https://github.com/octokit/octokit.rb/blob/ae1636f71fb02e0b858f54f755b5701d5fcb06ac/lib/octokit/client/organizations.rb#L623-L636

`add_team_membership` does take `maintainer` [as a parameter](https://developer.github.com/v3/orgs/teams/#parameters-2) while `add_team_member` does not.

`add_team_member` is also using the deprecated API https://developer.github.com/v3/orgs/teams/#deprecation-notice-1 😄 

Hope this helps!

**Comment by tarebyte** [comment]
Closing due to staleness
