### ISSUE TITLE
Octokit::UnprocessableEntity: 422 - Invalid request. "sha" wasn't supplied.

### ISSUE THREAD

**Issue by jonhue** [octokit/octokit.rb#992]
Here is the error I am getting:

```
Octokit::UnprocessableEntity: PUT https://api.github.com/repos/organization/repo/contents/config.xml: 422 - Invalid request.

"sha" wasn't supplied. // See: https://developer.github.com/v3/repos/contents/#update-a-file
from C:/Dev/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/octokit-4.8.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
```

I am trying to upload the contents of an entire folder to GitHub:

```ruby
Dir.glob(folder + '/**/*') do |path|
    octokit_client.create_contents 'organization/repo', path.sub("#{folder}/", ''), '🎉', File.read(path), branch: 'master' unless File.directory? path
end
```

The error occurs with the first attempt to upload a file.

**Comment by tarebyte** [comment]
It looks like the API is working as expected, it looks like you are missing the sha in your request.

From https://developer.github.com/v3/repos/contents/#update-a-file
> | Name | Type | Description |
> | --- | --- | ---|
> | `sha` | `string` | **Required.** The blob SHA of the file being replaced. |

So your code might need to look more like this

```ruby
Dir.glob(folder + '/**/*') do |path|
  next unless File.directory?(path)
  octokit_client.create_contents 'organization/repo', path.sub("#{folder}/", ''), '🎉', File.read(path), sha: '495565432a0cafb21a06389581ee36169ab5cb34', branch: 'master'
end
```

Hope this helps!

**Comment by jonhue** [comment]
@tarebyte 

Thanks for your help! I think you meant `next if File.directory?(path)` instead of `next unless File.directory?(path)`

I now get the following error, after adding the `sha` option:

```
Octokit::Conflict: PUT https://api.github.com/repos/organization/repo/contents/config.xml: 409 - config.xml does not match 495565432a0cafb21a06389581ee36169ab5cb34 // See: https://developer.github.com/v3/repos/contents/#update-a-file
from C:/Dev/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/octokit-4.8.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
```

**Comment by tarebyte** [comment]
I sure did 😅 and the sha I added was just an example, you'll need to provide your own.

**Comment by jonhue** [comment]
@tarebyte 

How do I get the `sha` I need?

**Comment by jonhue** [comment]
@tarebyte 

This issue is weird... I did some more testing - and sometimes the code I provided does work just fine, whereas most of the time it throws an error.

**Comment by jonhue** [comment]
@tarebyte

This issue is still occurring. Could you reopen it?

**Comment by tarebyte** [comment]
@jonhue so I think I see why you're getting the intermittent error.

If you are creating something new you don't need the `sha` https://developer.github.com/v3/repos/contents/#create-a-file

But if you are updating content you do need the sha https://developer.github.com/v3/repos/contents/#update-a-file

So the reason you're getting the `409` conflict is because you're not checking to see if the content is there first before trying to create/update it.

Does that sound about right?

As for reopening it, this is more of a problem with the GitHub API not Octokit the gem directly so I'm inclined to keep it closed.

**Comment by jonhue** [comment]
@tarebyte This was my initial thought as well. But it is not the case. Here is what I do:

1) delete repo if a repository with name exists
2) create repository
3) add contents

After the error occurred and the script stopped, the repo has been created but it is empty. There is no way that a file could not upload because another file already exists.

**Comment by kytrinyx** [comment]
Just catching up on this discussion. I'm going to go ahead and reopen this until we get all the questions sorted out.

**Comment by kytrinyx** [comment]
Ok, I *think* I've caught up, and I changed my mind about reopening this... as far as I can tell, the API and the octokit.rb client are working as expected.

@jonhue would you mind bringing your questions to support@github.com? It sounds like you're stuck on how to call the API rather than this being a bug, and support is a better venue for that.

**Comment by jonhue** [comment]
@kytrinyx 

GitHub Support wasn't really helpful. It said they don't provide support for this library and I should give them the response to the `curl` command, which I don't have.

I listed here how I am calling the GitHub API, what's wrong with it?

**Comment by kytrinyx** [comment]
@jonhue Yes, that's correct; Support doesn't provide support for the library. From my reading of the previous discussion, I was under the impression that you're having trouble with the API itself, not with the library.

Would you please list the exact commands that you're having trouble with? If possible, create a small reproducible test case.

**Comment by jonhue** [comment]
@kytrinyx Here is what I do:

1) delete repo if a repository with name exists
2) create repository
3) add contents
```ruby
Dir.glob(folder + '/**/*') do |path|
  next if File.directory?(path)
  octokit_client.create_contents 'organization/repo', path.sub("#{folder}/", ''), '🎉', File.read(path), branch: 'master'
end
```

This error is super weird. I did upload content in this way for a long time without having any problems. This error just recently popped up, but most of the time creating content through the API works well. I haven't noticed a pattern yet.

**Comment by kytrinyx** [comment]
If you don't do this in a loop, but do it with a specific path, does it work?
If it doesn't work, are you able to create something with just a single, simple text file rather than an entire directory?
If not, are you able to do it with plain text instead of emoji as your argument?

**Comment by jonhue** [comment]
1) Yes it does work. But mostly my current solution works well too.
2) ...
3) I previously used plain text and it did not make any difference.

**Comment by kytrinyx** [comment]
@jonhue I'm trying to help you narrow down your problem. If your solution mostly works, then this is very unlikely to be a problem in the Octokit client.

If it mostly currently works, then I'd suggest that you find a way to pinpoint the use case where it _doesn't_ work. Without a failing case we can't give you any pointers.

**Comment by kytrinyx** [comment]
@jonhue Since this is not a problem with the library itself, I'm going to go ahead and lock this issue.

I'd recommend that you get help with your debugging troubles in the wonderful CodeNewbie forum or slack: https://www.codenewbie.org/ -- it's a great, supportive community of people learning together.

If you are able to pinpoint a failing case that points to a bug in octokit, then please open a new issue.
